name: Videotheque
description: >-
    Gérer votre bibliothèque de films ! Cherchez, Ajoutez, Triez, Le tour est
    joué !
version: 2.5.0
environment:
    sdk: '>=2.1.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    shared_preferences: ^0.5.6
    http: 0.12.0+2
    webview_flutter: 0.3.18+1
    url_launcher: ^5.4.1
    flutter_launcher_icons: ^0.7.4
    firebase: ^7.1.0
    skeleton_text: ^1.0.0
    sliver_scaffold: ^0.0.7
    cupertino_icons: ^0.1.2
    progressive_image: ^1.0.1
    bottom_navy_bar: ^5.3.2
    flutter_custom_clippers: ^1.1.0
    drop_cap_text: ^1.0.7
    background_app_bar: ^1.0.1
    flutter_speed_dial: ^1.2.5
    community_material_icon: ^3.5.95
    intl: ^0.16.1
    keyboard_utils: ^1.2.0
    uuid: ^2.0.4
    flutter_native_splash: ^0.1.9
    provider: ^4.0.4

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter_icons:
    android: launcher_icon
    ios: false
    image_path_android: icon.png
flutter:
    uses-material-design: true
    assets:
        - assets/loading.png
    fonts:
        -
            family: Aladin
            fonts:
                -
                    asset: fonts/title.ttf
        -
            family: itty
            fonts:
                -
                    asset: fonts/itty.otf
        -
            family: Rubik
            fonts:
                -
                    asset: fonts/Rubik-Medium.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages